# Generated by Django 2.1.2 on 2018-10-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0002_user_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
    ]
